import type { Metadata } from "next";
import { Inter, Audiowide } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Image from "next/image";
import CheckWhite from "@/public/icons/check-white.svg";

const inter = Inter({ subsets: ["latin"] });
const audiowide = Audiowide({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={audiowide.className}>
          {children}
        </div>
        <Toaster
          position='top-center'
          visibleToasts={1}
          toastOptions={{
            unstyled: true,
            duration: 3000,
            classNames: {
              success: "bg-[#32A852] text-[#ffffff] text-bold flex flex-row items-center rounded-md h-[50px] px-4 shadow-md w-[360px]",
              error: "bg-red-600 text-[#ffffff] text-bold flex flex-row items-center rounded-md h-[50px] px-4 shadow-md w-[360px]",
            },
          }}
          icons={{
            success: <Image src={CheckWhite} alt="icon" width={40} height={40} />,
            error: <Image src={CheckWhite} alt="icon" width={40} height={40} />
          }}
        />
      </body>
    </html>
  );
}
